import * as path from "node:path";
import { isEntry } from "@brianjenkins94/util/env";
import { juvy } from "@brianjenkins94/util/juvy";
import { command, run } from "@brianjenkins94/util/juvy/cli";
import { ESLint } from "eslint";

/**
 * The `util-lint` bin. Run from a package directory (`"lint": "util-lint"`, or
 * `"lint:fix": "util-lint --fix"`) to lint that package's cwd with the shared
 * flat-config preset. A consumer only re-exports the preset from its own
 * eslint.config.js (`export { default } from "@brianjenkins94/util/eslint"`) —
 * the whole eslint toolchain ships with util, so no eslint deps of its own.
 *
 * Uses the ESLint Node API rather than spawning the `eslint` bin so it resolves
 * from util's dependencies regardless of the consumer's node_modules layout.
 */
export async function lint({ fix = false, patterns = ["."] }: { "fix"?: boolean; "patterns"?: string[] } = {}) {
	const eslint = new ESLint({ "cwd": process.cwd(), "fix": fix });

	const results = await eslint.lintFiles(patterns);

	if (fix) {
		await ESLint.outputFixes(results);
	}

	// ONLY errors fail the build (warnings never do — see the exit-code handler), but the stylish formatter
	// interleaves the two, so a couple of build-breaking errors hide among hundreds of warnings and are murder to
	// find. Print a compact errors-only digest FIRST — before the full stylish output — so the exact reason for the
	// failure is at the TOP: it's the first thing you see, and it survives a CI runner truncating a long log from the
	// end (which can eat the stylish tail, and with it the errors, entirely). Silent when there are no errors.
	const errors = results.flatMap((result) => result.messages
		.filter((message) => message.severity === 2)
		.map((message) => ({ "file": result.filePath, "line": message.line ?? 0, "column": message.column ?? 0, "message": message.message, "ruleId": message.ruleId ?? "parse-error" })));

	if (errors.length > 0) {
		const lines = errors.map((error) => `  ${path.relative(process.cwd(), error.file) || error.file}:${error.line}:${error.column}  ${error.message}  ${error.ruleId}`);

		process.stdout.write(`✖ ${errors.length} error${errors.length === 1 ? "" : "s"} (only errors fail the build; warnings do not):\n${lines.join("\n")}\n\n`);
	}

	const formatter = await eslint.loadFormatter("stylish");
	const output = await formatter.format(results);

	if (output !== "") {
		process.stdout.write(output.endsWith("\n") ? output : output + "\n");
	}

	return results.reduce((total, result) => total + result.errorCount, 0);
}

// Run directly (the `util-lint` bin): `util-lint [--fix] [patterns...]`. juvy owns parsing, validation, and
// autogenerated `--help`. Both leaves opt out of env (`env: false`) so a stray `FIX`/`PATTERNS` variable can't
// change what a consumer's `"lint": "util-lint"` does. The handler reports eslint's verdict through
// `process.exitCode`, which `run()` (default `exit: true`) turns into the process's exit status.
if (isEntry(import.meta)) {
	const config = juvy({
		"fix": { "format": Boolean, "default": false, "env": false, "doc": "Write eslint's auto-fixes back to disk." },
		"patterns": { "format": Array, "default": ["."], "positional": "rest", "env": false, "doc": "Files/globs to lint (default: the cwd)." }
	});

	await run(command({
		"name": "util-lint",
		"description": "Lint the cwd (or the given patterns) with util's shared eslint preset.",
		config,
		"handler": async (cfg) => {
			process.exitCode = (await lint({ "fix": cfg.get("fix"), "patterns": cfg.get("patterns") })) > 0 ? 1 : 0;
		}
	}));
}
