import * as path from "node:path";
import * as url from "node:url";
import { log } from "@brianjenkins94/util/logger";
import * as fs from "@brianjenkins94/util/fs";
import { createServer, serveStatic } from "@brianjenkins94/util/server";
import { juvy } from "@brianjenkins94/util/juvy";
import { command, run } from "@brianjenkins94/util/juvy/cli";

type Server = ReturnType<typeof createServer>;

export interface ServeStaticOptions {
	/** Directory to serve, resolved against the cwd. Defaults to the cwd. */
	"dir"?: string;
	/** Port to listen on. Defaults to 3000. */
	"port"?: number;
	/** Mount the site under `/<base>` instead of at the root — mirrors a GitHub Pages `/<repo>/` deploy so
	 *  base-relative URLs and a service-worker scope behave locally as they will in production. The root
	 *  redirects to `/<base>/`. Leading/trailing slashes are optional. Omit to serve at `/`. */
	"base"?: string;
}

async function exists(file: string): Promise<boolean> {
	return fs.stat(file).then(() => true, () => false);
}

/**
 * The zero-config profile — resolve {@link ServeStaticOptions} purely from convention, so the
 * `util-serve` bin runs with no arguments. Serves the first of `docs/`/`_site/` that exists (the
 * base-agnostic output {@link buildStatic}/`util-build-static` produces), else the cwd; port from
 * `$PORT`, else 3000. Override any piece by spreading: `serve({ ...await discoverServeConfig(), port })`.
 */
export async function discoverServeConfig(root = process.cwd()): Promise<Required<Omit<ServeStaticOptions, "base">>> {
	let dir = root;

	for (const candidate of ["docs", "_site"].map((name) => path.resolve(root, name))) {
		if (await exists(candidate)) { dir = candidate; break; }
	}

	return { dir, "port": process.env["PORT"] !== undefined ? Number(process.env["PORT"]) : 3000 };
}

/**
 * Serve a directory of static files over HTTP — the local counterpart to `util-build-static`, for
 * previewing a base-agnostic static build. Reuses `serveStatic` (index.html fallback + path-traversal
 * guard) on the shared `createServer`; the dir is resolved to an absolute path so that guard holds. With
 * a `base`, the site mounts under `/<base>` (the wildcard strips the prefix, so `serveStatic` still sees
 * a dir-relative path) and the root redirects to `/<base>/`. Resolves once listening, with the server
 * (call `.close()` to stop). Consumed as `@brianjenkins94/util/scripts/serve`; the `util-serve` bin runs
 * it with a convention-resolved dir/port.
 */
export async function serve(options: ServeStaticOptions = {}): Promise<Server> {
	const dir = path.resolve(options.dir ?? process.cwd());
	const port = options.port ?? 3000;
	const base = options.base?.replace(/^\/+|\/+$/gu, ""); // normalize `/repo/` | `repo` → `repo`

	const server = createServer();

	if (base) {
		const prefix = "/" + base;

		server.get(prefix + "/*", serveStatic(dir));
		// Bare `/<base>` (no trailing slash) and `/` both land on the mounted root.
		server.get(prefix, (_request, response) => response.redirect(prefix + "/"));
		server.get("/", (_request, response) => response.redirect(prefix + "/"));
	} else {
		server.get("/*", serveStatic(dir));
	}

	return new Promise((resolve) => {
		server.listen(port, () => {
			log.info("serving static", { dir, "url": `http://localhost:${port}${base ? "/" + base : ""}/` });
			resolve(server);
		});
	});
}

// Run directly (the `util-serve` bin): `util-serve [dir] [--port N] [--base <prefix>]`. juvy owns parsing,
// validation, and autogenerated `--help`: `dir` is a positional, `--port`/`--base` are flags; the convention
// profile (docs/ ­→ _site/ → cwd, `$PORT`) supplies the defaults. `exit: false` so the listening server isn't
// killed after the handler starts it.
if (process.argv[1] !== undefined && import.meta.url === url.pathToFileURL(await fs.realpath(process.argv[1])).toString()) {
	const discovered = await discoverServeConfig();

	const config = juvy({
		"dir": { "format": String, "default": discovered.dir, "positional": true, "env": false, "doc": "Directory to serve (default: docs/, _site/, or .)." },
		"port": { "format": "port", "default": discovered.port, "short": "p", "env": false, "doc": "Port to listen on ($PORT)." },
		"base": { "format": String, "default": "", "short": "b", "env": false, "doc": "Mount under /<base> (mirror a Pages /<repo>/ deploy)." }
	});

	await run(command({
		"name": "util-serve",
		"description": "Serve a directory of static files (a local GitHub Pages mirror).",
		config,
		"handler": (cfg) => serve({ "dir": cfg.get("dir"), "port": cfg.get("port"), "base": cfg.get("base") })
	}), { "exit": false });
}
