{
  "name": "cd",
  "on": {
    "workflow_dispatch": null
  },
  "concurrency": {
    "group": "${{ github.workflow }}-${{ github.ref }}",
  },
  "permissions": {
    "contents": "read",
    "pages": "write",
    "id-token": "write"
  },
  "jobs": {
    "changes": {
      "runs-on": "ubuntu-latest",
      "steps": [
        { "uses": "actions/checkout@v4" },
        {
          "id": "enumerate",
          "run": "echo PACKAGES=\"$(git ls-files */package.json */*/package.json  --exclude=.* --exclude=**/node_modules/* | jq --compact-output --raw-input --slurp 'split(\"\\n\")[:-1] | map(sub(\"/package.json$\"; \"\")) | reduce .[] as $key ({}; .[$key] = \"\\($key)/**\")')\" >> $GITHUB_OUTPUT"
        },
        {
          "if": "steps.enumerate.outputs.PACKAGES != '{}'",
          "uses": "dorny/paths-filter@v2",
          "id": "filter",
          "with": {
            "filters": "${{ steps.enumerate.outputs.PACKAGES }}"
          }
        }
      ],
      "outputs": {
        "packages": "${{ steps.filter.outputs.changes }}"
      },
      "timeout-minutes": 15
    },
    "release": {
      "if": "needs.changes.outputs.packages != '' && needs.changes.outputs.packages != '[]'",
      "runs-on": "ubuntu-latest",
      "needs": ["changes"],
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "package": "${{ fromJSON(needs.changes.outputs.packages) }}"
        }
      },
      "steps": [
        { "uses": "actions/checkout@v3" },
        { "uses": "actions/setup-node@v3", "with": { "node-version": 22 } },
        { "run": "npm install" }, #{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
        {
          "working-directory": "${{ matrix.package }}",
          "run": "npm run build --if-present"
        },

        {
          "id": "tag",
          "env": {
            "GH_TOKEN": "${{ secrets.PAT }}"
          },
          "working-directory": "${{ matrix.package }}",
          "run": "PACKAGE=\"${{ matrix.package }}\"; TAG_NAME=$(jq --raw-output 'select(.version != null and .version != \"\") | \"\\(.name)@\\(.version)\"' package.json || true); if [[ -z \"$TAG_NAME\" ]] || gh release list --json tagName --jq '.[].tagName' | grep -qx \"$TAG_NAME\"; then BASE_VERSION=$(gh release list --json tagName --jq \"([.[] | select(.tagName | startswith(\\\"${PACKAGE}@\\\")) | .tagName] | map(sub(\\\"${PACKAGE}@\\\"; \\\"\\\")) | map(split(\\\".\\\") | map(tonumber)) | sort | last | if . == null then \\\"0.0.0\\\" else (map(tostring) | join(\\\".\\\")) end)\"); TAG_NAME=\"${PACKAGE}@$(npx -y semver $BASE_VERSION -i minor)\"; fi; echo \"TAG_NAME=$TAG_NAME\" >> \"$GITHUB_OUTPUT\""
        },
        {
          "uses": "softprops/action-gh-release@v2",
          "with": {
            "draft": true,
            "tag_name": "${{ steps.tag.outputs.TAG_NAME }}",
            "token": "${{ secrets.PAT }}"
          }
        }
      ],
      "timeout-minutes": 15
    },
    "build": {
      "runs-on": "ubuntu-latest",
      "needs": ["changes", "release"],
      "steps": [
        { "uses": "actions/checkout@v4" },
        { "uses": "actions/setup-node@v4", "with": { "node-version": 22 } },

        {
          "env": {
            "GH_TOKEN": "${{ secrets.PAT }}"
          },
          "run": "RUN_ID=$(gh run list --workflow=cd.yml --json databaseId,status,conclusion --jq '[.[] | select(.status == \"completed\" and .conclusion == \"success\")][0].databaseId'); if [[ -n \"$RUN_ID\" ]]; then gh run download \"$RUN_ID\" --name cd; tar -xvf cd.tar --keep-old-files --directory docs/; fi"
        },

        { "run": "npm install" }, #{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
        { "run": "npm run publish" },

        {
          "env": {
            "GH_TOKEN": "${{ secrets.PAT }}"
          },
          "run": "for PACKAGE in $(jq -r '.[]' <<< '${{ needs.changes.outputs.packages }}'); do TAG_NAME=$(jq -r 'select(.version != null and .version != \"\") | \"\\(.name)@\\(.version)\"' \"$PACKAGE/package.json\"); ARCHIVE=\"docs/${TAG_NAME}.tgz\"; if [[ -f \"$ARCHIVE\" ]]; then echo \"Promoting $TAG_NAME\"; gh release edit \"$TAG_NAME\" --draft=false; else echo \"Deleting $TAG_NAME (not published)\"; gh release delete \"$TAG_NAME\" --yes || true; git push origin \":refs/tags/$TAG_NAME\" || true; fi; done"
        },

        {
          "uses": "actions/upload-pages-artifact@v3",
          "with": {
            "path": "./docs"
          }
        }
      ],
      "timeout-minutes": 15
    },
    "deploy": {
      "runs-on": "ubuntu-latest",
      "environment": {
        "name": "github-pages",
        "url": "${{ steps.deployment.outputs.page_url }}"
      },
      "needs": ["build"],
      "steps": [
        {
          "id": "deployment",
          "uses": "actions/deploy-pages@v4"
        }
      ],
      "timeout-minutes": 15
    }
  }
}
