{
  "name": "ci",
  "on": {
    "push": {
      "branches": ["main"]
    }
  },
  "concurrency": {
    "group": "${{ github.workflow }}-${{ github.ref }}",
    "cancel-in-progress": true
  },
  "jobs": {
    "build-lint-test": {
      "runs-on": "ubuntu-latest",
      "strategy": {
        "matrix": {
          "script": ["build", "lint", "test"]
        }
      },
      "steps": [
        { "uses": "actions/checkout@v4" },
        { "uses": "actions/setup-node@v4", "with": { "node-version": 22 } },
        { "run": "npm install" }, #{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
        { "run": "npm run ${{ matrix.script }} --if-present" }
      ],
      "timeout-minutes": 15
    },
    "dispatch": {
      "runs-on": "ubuntu-latest",
      "needs": ["build-lint-test"],
      "uses": "brianjenkins94/lib/.github/workflows/cd.yml@main",
      "secrets": {
        "GH_TOKEN": "${{ secrets.PAT }}"
      },
      "timeout-minutes": 15
    }
  }
}
