{
  "name": "ci",
  "on": {
    "push": {
      "branches": ["main"]
    }
  },
  "concurrency": {
    "group": "${{ github.ref }}",
    "cancel-in-progress": true
  },
  "jobs": {
    "build-lint-test": {
      "runs-on": "ubuntu-latest",
      "strategy": {
        "matrix": {
          "script": ["build", "lint", "test"]
        }
      },
      "steps": [
        { "uses": "actions/checkout@v4" },
        { "uses": "actions/setup-node@v4", "with": { "node-version": 22 } },
        { "run": "npm install" }, #{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
        #{ "run": "npm run build" },
        { "run": "npx tsx util/tree.ts" },
        { "run": "npm run ${{ matrix.script }} --if-present" }
      ],
      "timeout-minutes": 15
    },
    "changes": {
      "runs-on": "ubuntu-latest",
      "needs": ["build-lint-test"],
      "steps": [
        { "uses": "actions/checkout@v4" },
        {
          "id": "enumerate",
          "run": "echo PACKAGES=\"$(find . -mindepth 2 -maxdepth 4 -name \"package.json\" -not -path \"*/.*\" -not -path \"*/node_modules/**\" -exec dirname {} + | jq --compact-output --null-input --raw-input --slurp 'input | split(\"\\n\")[:-1] | reduce .[][2:] as $key ({}; .[$key] = \"\\($key)/**\")')\" >> $GITHUB_OUTPUT"
        },
        {
          "if": "steps.enumerate.outputs.PACKAGES != '{}'",
          "uses": "dorny/paths-filter@v2",
          "id": "filter",
          "with": {
            "filters": "${{ steps.enumerate.outputs.PACKAGES }}"
          }
        }
      ],
      "outputs": {
        "packages": "${{ steps.filter.outputs.changes }}"
      },
      "timeout-minutes": 15
    },
    "release": {
      "if": "needs.changes.outputs.packages != '' && needs.changes.outputs.packages != '[]'",
      "runs-on": "ubuntu-latest",
      "needs": ["changes"],
      "strategy": {
        "matrix": {
          "package": "${{ fromJSON(needs.changes.outputs.packages) }}"
        }
      },
      "steps": [
        { "uses": "actions/checkout@v3" },
        { "uses": "actions/setup-node@v3", "with": { "node-version": 22 } },
        { "run": "npm install" }, #{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
        #{ "run": "npm run build" },
        {
          "env": {
            "GH_TOKEN": "${{ secrets.PAT }}"
          },
          "run": "if [[ -z \"$GH_TOKEN\" ]]; then echo \"GH_TOKEN is not set or is empty.\"; else echo \"GH_TOKEN is set.\"; fi"
        },
        {
        	"id": "tag",
          "env": {
            "GH_TOKEN": "${{ secrets.PAT }}"
          },
          "working-directory": "${{ matrix.package }}",
          "run": "PACKAGE=\"${{ matrix.package }}\"; TAG_NAME=$(jq --raw-output 'select(.version != null and .version != \"\") | \"\\(.name)-\\(.version)\"' package.json || true); if [[ -n \"$TAG_NAME\" ]] && ! gh release list --json tagName --jq '.[].tagName' | grep -qx \"$TAG_NAME\"; then echo \"tag=$TAG_NAME\" >> \"$GITHUB_OUTPUT\"; else TAG_NAME=$(gh release list --json tagName --jq \"([.[] | select(.tagName | startswith(\\\"${PACKAGE}-\\\")) | .tagName] | map(sub(\\\"${PACKAGE}-\\\"; \\\"\\\")) | map(split(\\\".\\\") | map(tonumber)) | sort | last | if . == null then null else map(tostring) | join(\\\".\\\") | \\\"${PACKAGE}-\\\" + .) // \\\"${PACKAGE}-0.1.0\\\"\"); echo \"tag=$TAG_NAME\" >> \"$GITHUB_OUTPUT\"; fi"
        },
        {
          "uses": "softprops/action-gh-release@v2",
          "with": {
            "tag_name": "steps.tag.outputs.TAG_NAME",
            "token": "${{ secrets.PAT }}"
          }
        }
      ],
      "timeout-minutes": 15
    },
    "publish": {
      "runs-on": "ubuntu-latest",
      "needs": ["changes", "release"],
      "steps": [
        {
          "env": {
            "GH_TOKEN": "${{ secrets.PAT }}"
          },
          "run": "if [[ -z \"$GH_TOKEN\" ]]; then echo \"GH_TOKEN is not set or is empty.\"; else echo \"GH_TOKEN is set.\"; fi"
        },
        {
          "env": {
            "GH_TOKEN": "${{ secrets.PAT }}"
          },
          "run": "gh workflow run cd"
        }
      ],
      "timeout-minutes": 15
    }
  }
}
